exports.data = [
    {
        name: "Splatterella",
        description: "Llamas beware.",
        type: "outfit",
        rarity: "rare",
        series: "",
        cost: 1200,
        imgIcon: "./images/splatterella.png",
        imgFeatured: "./images/splatterella.png",
        avgStars: 3.88,
        firstOccurrences: "21-04-2021",
        lastOccurrences: "21-04-2021",
        occurrences: 1,
        stock: 5,
        isNew: "true"
    },
    {
        name: "Lovethorn (Dark)",
        description: "The dark side of romance.",
        type: "outfit",
        rarity: "epic",
        series: "",
        cost: 100,
        imgIcon: "./images/lovethorn-dark.png",
        imgFeatured: "./images/lovethorn-dark.png",
        avgStars: 3.98,
        firstOccurrences: "21-04-2021",
        lastOccurrences: "21-04-2021",
        occurrences: 1,
        stock: 10,
        isNew: "true"
    },
    {
        name: "Rebirth Raven (Classic)",
        description: "",
        type: "outfit",
        rarity: "rare",
        series: "dc",
        cost: 100,
        imgIcon: "./images/raven-classic.png",
        imgFeatured: "./images/raven-classic.png",
        avgStars: 3.5,
        firstOccurrences: "21-04-2021",
        lastOccurrences: "21-04-2021",
        occurrences: 1,
        stock: 10,
        isNew: "true"
    },
    {
        name: "Snap",
        description: "Make it snappy.",
        type: "emote",
        rarity: "uncommon",
        series: "",
        cost: 100,
        imgIcon: "./images/snap.png",
        imgFeatured: "./images/snap.png",
        avgStars: 4.27,
        firstOccurrences: "21-04-2021",
        lastOccurrences: "21-04-2021",
        occurrences: 1,
        stock: 10,
        isNew: "true"
    },
    {
        name: "Redux",
        description: "Revived. Rebuilt. Ready for revenge.",
        type: "outfit",
        rarity: "rare",
        series: "",
        cost: 100,
        imgIcon: "./images/redux.png",
        imgFeatured: "./images/redux.png",
        avgStars: 3.42,
        firstOccurrences: "21-04-2021",
        lastOccurrences: "21-04-2021",
        occurrences: 1,
        stock: 10,
        isNew: "true"
    },
    {
        name: "Air Shredder",
        description: "The guitar is in your mind.",
        type: "emote",
        rarity: "rare",
        series: "",
        cost: 100,
        imgIcon: "./images/air-shredder.png",
        imgFeatured: "./images/air-shredder.png",
        avgStars: 3.36,
        firstOccurrences: "21-04-2021",
        lastOccurrences: "21-04-2021",
        occurrences: 1,
        stock: 10,
        isNew: "true"
    },
    {
        name: "Starshot",
        description: "You've got star power.",
        type: "pickaxe",
        rarity: "uncommon",
        series: "",
        cost: 500,
        imgIcon: "./images/starshot.png",
        imgFeatured: "./images/starshot.png",
        avgStars: 3.59,
        firstOccurrences: "21-04-2021",
        lastOccurrences: "21-04-2021",
        occurrences: 1,
        stock: 10,
        isNew: "false"
    },
    {
        name: "Cozy Chomps",
        description: "Take life one chomp at a time.",
        type: "outfit",
        rarity: "rare",
        series: "",
        cost: 1200,
        imgIcon: "./images/cozy-chomps.png",
        imgFeatured: "./images/cozy-chomps.png",
        avgStars: 3.98,
        firstOccurrences: "21-04-2021",
        lastOccurrences: "21-04-2021",
        occurrences: 1,
        stock: 10,
        isNew: "false"
    },
    {
        name: "Sharky",
        description: "Show your style.",
        type: "wrap",
        rarity: "uncommon",
        series: "",
        cost: 300,
        imgIcon: "./images/sharky-wrap.png",
        imgFeatured: "./images/sharky-wrap.png",
        avgStars: 3.8,
        firstOccurrences: "21-04-2021",
        lastOccurrences: "21-04-2021",
        occurrences: 1,
        stock: 10,
        isNew: "false"
    },
    {
        name: "Eco",
        description: "He's got it all mapped out.",
        type: "outfit",
        rarity: "epic",
        series: "",
        cost: 1500,
        imgIcon: "./images/eco.png",
        imgFeatured: "./images/eco.png",
        avgStars: 4.04,
        firstOccurrences: "21-04-2021",
        lastOccurrences: "21-04-2021",
        occurrences: 1,
        stock: 10,
        isNew: "false"
    },
    {
        name: "Sharky Slappers",
        description: "The power of a shark. The convenience of a slap.",
        type: "pickaxe",
        rarity: "uncommon",
        series: "",
        cost: 500,
        imgIcon: "./images/sharky-slappers.png",
        imgFeatured: "./images/sharky-slappers.png",
        avgStars: 3.89,
        firstOccurrences: "21-04-2021",
        lastOccurrences: "21-04-2021",
        occurrences: 1,
        stock: 10,
        isNew: "false"
    },
    {
        name: "Metal Team Leader",
        description: "Totally metal.",
        type: "outfit",
        rarity: "rare",
        series: "",
        cost: 1200,
        imgIcon: "./images/metal-team-leader.png",
        imgFeatured: "./images/metal-team-leader.png",
        avgStars: 3.39,
        firstOccurrences: "21-04-2021",
        lastOccurrences: "21-04-2021",
        occurrences: 1,
        stock: 10,
        isNew: "false"
    },
    {
        name: "Doodle Buddies",
        description: "Show your style.",
        type: "wrap",
        rarity: "rare",
        series: "",
        cost: 500,
        imgIcon: "./images/doodle-buddies-wrap.png",
        imgFeatured: "./images/doodle-buddies-wrap.png",
        avgStars: 4.05,
        firstOccurrences: "21-04-2021",
        lastOccurrences: "21-04-2021",
        occurrences: 1,
        stock: 10,
        isNew: "false"
    },
    {
        name: "Castor",
        description: "The wandering warlock of Wailing Woods.",
        type: "outfit",
        rarity: "epic",
        series: "",
        cost: 1500,
        imgIcon: "./images/castor.png",
        imgFeatured: "./images/castor.png",
        avgStars: 3.9,
        firstOccurrences: "21-04-2021",
        lastOccurrences: "21-04-2021",
        occurrences: 1,
        stock: 10,
        isNew: "false"
    },
    {
        name: "Howl",
        description: "Stand in front of a moon for maximum effect.",
        type: "emote",
        rarity: "uncommon",
        series: "",
        cost: 200,
        imgIcon: "./images/howl.png",
        imgFeatured: "./images/howl.png",
        avgStars: 3.91,
        firstOccurrences: "21-04-2021",
        lastOccurrences: "21-04-2021",
        occurrences: 1,
        stock: 10,
        isNew: "false"
    },
    {
        name: "Party Hips",
        description: "Some strings attached.",
        type: "emote",
        rarity: "uncommon",
        series: "",
        cost: 200,
        imgIcon: "./images/party-hips.png",
        imgFeatured: "./images/party-hips.png",
        avgStars: 3.77,
        firstOccurrences: "21-04-2021",
        lastOccurrences: "21-04-2021",
        occurrences: 1,
        stock: 10,
        isNew: "false"
    },
    {
        name: "Star Power",
        description: "No autographs please.",
        type: "emote",
        rarity: "epic",
        series: "",
        cost: 800,
        imgIcon: "./images/star-power.png",
        imgFeatured: "./images/star-power.png",
        avgStars: 3.95,
        firstOccurrences: "21-04-2021",
        lastOccurrences: "21-04-2021",
        occurrences: 1,
        stock: 10,
        isNew: "false"
    },
    {
        name: "Cyber Infiltration Pack",
        description: "",
        type: "bundle",
        rarity: "rare",
        series: "",
        cost: 2200,
        imgIcon: "./images/cyber-infiltration-pack.png",
        imgFeatured: "./images/cyber-infiltration-pack.png",
        avgStars: 3.45,
        firstOccurrences: "21-04-2021",
        lastOccurrences: "21-04-2021",
        occurrences: 1,
        stock: 10,
        isNew: "false"
    },
    {
        name: "Infiltration Tools Pack",
        description: "",
        type: "bundle",
        rarity: "rare",
        series: "",
        cost: 1200,
        imgIcon: "./images/infiltration-tools-pack.png",
        imgFeatured: "./images/infiltration-tools-pack.png",
        avgStars: 3.43,
        firstOccurrences: "21-04-2021",
        lastOccurrences: "21-04-2021",
        occurrences: 1,
        stock: 10,
        isNew: "false"
    },
    {
        name: "Cuddle King",
        description: "Love rules all.",
        type: "outfit",
        rarity: "rare",
        series: "",
        cost: 1200,
        imgIcon: "./images/cuddle-king.png",
        imgFeatured: "./images/cuddle-king.png",
        avgStars: 3.66,
        firstOccurrences: "21-04-2021",
        lastOccurrences: "21-04-2021",
        occurrences: 1,
        stock: 10,
        isNew: "false"
    },
    {
        name: "Terns",
        description: "The spirit of the forest.",
        type: "outfit",
        rarity: "epic",
        series: "",
        cost: 1200,
        imgIcon: "./images/terns.png",
        imgFeatured: "./images/terns.png",
        avgStars: 3.96,
        firstOccurrences: "21-04-2021",
        lastOccurrences: "21-04-2021",
        occurrences: 1,
        stock: 10,
        isNew: "false"
    },
    {
        name: "Codename E.L.F.",
        description: "Elusive. Lethal. Festive.",
        type: "outfit",
        rarity: "rare",
        series: "",
        cost: 1200,
        imgIcon: "./images/codename.png",
        imgFeatured: "./images/codename.png",
        avgStars: 4,
        firstOccurrences: "21-04-2021",
        lastOccurrences: "21-04-2021",
        occurrences: 1,
        stock: 10,
        isNew: "false"
    },
    {
        name: "Menace (Challenger)",
        description: "",
        type: "outfit",
        rarity: "legendary",
        series: "",
        cost: 1200,
        imgIcon: "./images/menace-challenger.png",
        imgFeatured: "./images/menace-challenger.png",
        avgStars: 3.92,
        firstOccurrences: "21-04-2021",
        lastOccurrences: "21-04-2021",
        occurrences: 1,
        stock: 10,
        isNew: "false"
    },
    {
        name: "Vendetta (Orange)",
        description: "Upgrade and override.",
        type: "outfit",
        rarity: "legendary",
        series: "",
        cost: 1200,
        imgIcon: "./images/vendetta-orange.png",
        imgFeatured: "./images/vendetta-orange.png",
        avgStars: 3.85,
        firstOccurrences: "21-04-2021",
        lastOccurrences: "21-04-2021",
        occurrences: 1,
        stock: 10,
        isNew: "false"
    },
    {
        name: "Deadpool (No Mask)",
        description: "The merc with a mouth.",
        type: "outfit",
        rarity: "legendary",
        series: "marvel",
        cost: 1200,
        imgIcon: "./images/deadpool-no-mask.png",
        imgFeatured: "./images/deadpool-no-mask.png",
        avgStars: 3.43,
        firstOccurrences: "21-04-2021",
        lastOccurrences: "21-04-2021",
        occurrences: 1,
        stock: 10,
        isNew: "false"
    },
    {
        name: "Frozen Love Ranger",
        description: "Aim for the cold-hearted.",
        type: "outfit",
        rarity: "legendary",
        series: "frozen",
        cost: 1200,
        imgIcon: "./images/frozen-love-ranger.png",
        imgFeatured: "./images/frozen-love-ranger.png",
        avgStars: 3.97,
        firstOccurrences: "21-04-2021",
        lastOccurrences: "21-04-2021",
        occurrences: 1,
        stock: 10,
        isNew: "false"
    },
    {
        name: "Thor (Silver Foil)",
        description: "Son of Odin. God of Thunder.",
        type: "outfit",
        rarity: "epic",
        series: "marvel",
        cost: 1200,
        imgIcon: "./images/thor-silver.png",
        imgFeatured: "./images/thor-silver.png",
        avgStars: 3.32,
        firstOccurrences: "21-04-2021",
        lastOccurrences: "21-04-2021",
        occurrences: 1,
        stock: 10,
        isNew: "false"
    }
    
];